import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/context/AuthContext"
import Menu from "@/components/layout/Header"
import Header from "@/components/layout/Header"
import Footer from "@/components/layout/Footer"

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <AuthProvider>
          <Header />
          <main className="pb-32">{children}</main>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  )
}
